
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 功能'
    labels:
      - 'feature'
      - 'enhancement'
      - '功能'
  - title: '🐛 Bug 修复'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - '缺陷'
  - title: '🧰 杂项'
    labels: 
      - 'chore'
      - 'support'
      - 'other'
      - '维护'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - 'release/skip'
autolabeler:
  - label: 'bug'
    branch:
      - '/bugfix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
template: |
  ## 最近更新
  
  $CHANGES