
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 更新功能'
    labels:
      - 'feature'
      - 'enhancement'
      - '功能'
      - '完善'
  - title: '🐛 缺陷修复'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - '缺陷'
  - title: '🧰 维护和其他'
    labels: 
      - 'chore'
      - 'support'
      - 'other'
      - '维护'
      - 'docs'
      - '文档'
change-template: '- (#$NUMBER) $TITLE - by @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - 'skip-release'
autolabeler:
  - label: '缺陷'
    branch:
      - '/bugfix\/.+/'
  - label: '功能'
    branch:
      - '/feature\/.+/'
  - label: '文档'
    branch:
      - '\/.+/(docs|doc)\/.+/'
  - label: '组件'
    branch:
      - '/feature/component\/.+/'
template: |  
  $CHANGES