name: 自动打包部署到 nuget 并生成 release note

on:
  pull_request:
        branches:
          - 'master'
    # tags:
    # - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Semver Parse
        uses: release-kit/semver@v1.0.10
      - name: Use parsed version
        run: |
          echo "----------output-----------"
          echo "${{ steps.version.outputs.major }}"
          echo "${{ steps.version.outputs.minor }}"
          echo "${{ steps.version.outputs.patch }}"
          echo "${{ steps.version.outputs.prerelease }}"
          echo "${{ steps.version.outputs.build }}"
          echo "${{ steps.version.outputs.full }}"
          echo "${{ steps.version.outputs.tag }}"

    
