name: 自动打包部署到 nuget 并生成 release note

on:
  pull_request:
        branches:
          - 'master'
    # tags:
    # - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git Version
        uses: codacy/git-version@2.5.4
    #- uses: actions/checkout@v3
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v2
    #  with:
    #    dotnet-version: 6.0.x
    #- name: 还原
    #  run: dotnet restore
    #- name: 编译
    #  run: dotnet build --no-restore
    #- name: 打包
    #  run: dotnet 
    
