name: 自动打包部署到 nuget 并生成 release note

on:
  pull_request:
        branches:
          - 'master'
    # tags:
    # - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Process version of the tag
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps.version.outputs) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump previous tag
        env:
          PREVIOUS_TAG: ${{ steps.version.outputs.previous_tag }}
        run: echo "$PREVIOUS_TAG"
    #- uses: actions/checkout@v3
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v2
    #  with:
    #    dotnet-version: 6.0.x
    #- name: 还原
    #  run: dotnet restore
    #- name: 编译
    #  run: dotnet build --no-restore
    #- name: 打包
    #  run: dotnet 
    
