name: 编译
run-name: 编译并测试

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 配置 .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: 还原包
      run: dotnet restore
    - name: 编译
      run: dotnet build --no-restore
    - name: 测试
      run: dotnet test
