name: PR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 配置 .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: 还原包
      run: dotnet restore
    - name: 编译
      run: dotnet build --no-restore
    - name: 测试
      run: |
        dotnet test --collect:"XPlat Code Coverage"
        find ./src/TDesignBlazor.Test/*TestResults* -name "*coverage*.xml" -type f -exec cp {} ./ \;
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        api-token: ${{ secrets.CODACY_ACCOUNT_TOKEN }}
        coverage-reports: 'coverage.cobertura.xml'
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v3
    #  with:
    #    token: ${{ secrets.CODECOV_TOKEN }}
    #    files: ./coverage.cobertura.xml,./cobertura-coverage.xml
    #    fail_ci_if_error: false

