name: ".NET 代码分析"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: .NET 代码分析
      uses: dotnet/code-analysis@v1
      id: code-analysis
      with:
        project: "./src/TDesignBlazor/TDesignBlazor.csproj"
        build-breaking: true
        all-categories: all